pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
            	bat 'c:'
            	bat 'cd C:/Users/42058/.jenkins/jobs/simple-java-maven-app'
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
